/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1bdd8052-a87f-4be8-aec3-25f30b4196d9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_1IW1Zp15l",
    "aws_user_pools_web_client_id": "2jnrpn325uksl67ojftim78k31",
    "oauth": {
        "domain": "oauthdemo0886fb5e-0886fb5e-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
